export const myInquiriesStyles = {
  loaderFullPage: "loader-full-page",
  loader: "loader",
  bgBgAltMinH: "bg-bg-alt min-h-screen",
  bgTransparentMinH: "bg-transparent min-h-screen",
  containerPy12TextCenter: "container py-12 text-center w-full mx-auto",
  cardPremiumPy16Px8: "card-premium py-16 px-4 md:px-8",
  textDangerMb4: "text-[var(--danger)] mb-4",
  mb8: "mb-8",
  btnPrimary: "btn btn-primary",
  bgTransparentHAuto: "bg-transparent h-auto w-full",
  containerFadeIn: "container fade-in w-full max-w-full px-4 sm:px-6 lg:px-8 overflow-hidden",
  py12Pt12: "py-12 pt-12",
  pt0: "pt-0",
  mb12: "mb-8 md:mb-12",
  heading: "text-[2rem] md:text-[2.5rem] mb-2 font-extrabold",
  textMuted: "text-text-muted text-sm md:text-base",
  cardPremiumPy24Px8TextCenter: "card-premium py-16 px-6 md:py-24 md:px-8 text-center",
  iconContainer: "bg-[#f8fafc] w-16 h-16 md:w-20 md:h-20 rounded-full flex items-center justify-center mx-auto mb-6 text-[#94a3b8]",
  mb4: "mb-4 text-xl md:text-2xl font-bold",
  textMutedMb8: "text-[#64748b] mb-8 text-sm md:text-base",
  flexColGap6: "flex flex-col gap-4 md:gap-6 w-full",
  inquiryCard: "card-premium p-5 md:p-6 lg:p-8 flex flex-col lg:flex-row justify-between items-start lg:items-stretch gap-6 overflow-hidden",
  inquiryMain: "flex flex-col sm:flex-row gap-4 md:gap-6 flex-1 w-full min-w-0",
  iconWrapper: "bg-primary-light p-3 md:p-4 rounded-xl text-primary h-fit shrink-0",
  iconSize: "w-5 h-5 md:w-6 md:h-6",
  flex1: "flex-1 min-w-0 w-full",
  titleRow: "flex items-start md:items-center justify-between md:justify-start gap-3 mb-3 flex-wrap",
  titleText: "text-[1.1rem] md:text-[1.25rem] font-bold text-text-main break-words",
  badge: "badge shrink-0 px-2 py-1 text-xs whitespace-nowrap",
  badgeRead: "bg-[#f1f5f9] text-[#64748b]",
  badgeNew: "bg-[#eff6ff] text-[#2563eb]",
  buyerInfo: "flex flex-col md:flex-row gap-3 md:gap-6 mb-5 p-3 md:p-4 bg-[#f8fafc] rounded-xl flex-wrap w-full",
  infoItem: "flex items-center gap-2 text-[0.85rem] md:text-sm text-[#475569] break-all sm:break-normal min-w-0",
  textMutedSmall: "text-[#94a3b8] shrink-0",
  fontSemibold: "font-semibold text-text-main",
  message: "text-[#334155] text-[0.95rem] md:text-base italic mb-5 pl-3 border-l-[3px] border-[#e2e8f0] break-words",
  meta: "flex flex-col sm:flex-row gap-2 sm:gap-6 text-[0.8rem] md:text-[0.8125rem] text-[#64748b] font-medium w-full flex-wrap",
  flexItemsCenterGap2: "flex items-center gap-1.5 whitespace-nowrap",
  actions: "flex flex-col sm:flex-row lg:flex-col gap-3 w-full lg:w-[160px] lg:shrink-0 lg:ml-6 pt-4 lg:pt-0 border-t border-[#f1f5f9] lg:border-t-0 justify-center",
  btnOutline: "btn btn-outline py-2.5 px-4 md:py-3 w-full justify-center flex items-center gap-2 text-sm",
  btnPrimaryWhitespaceNowrap: "btn btn-primary py-2.5 px-4 md:py-3 w-full justify-center text-sm",
  btnMessage: "btn py-2.5 px-4 md:py-3 w-full justify-center bg-[#2563eb] text-white hover:bg-[#1d4ed8] flex items-center gap-2 text-sm rounded-xl font-semibold shadow-sm",
};