export const sellerDashboardStyles = {
  header: "flex flex-col md:flex-row justify-between items-start mb-8 flex-wrap gap-6 md:gap-6",
  headerLeft: "min-w-0 w-full md:w-auto md:min-w-[280px]",
  headerTitle: "text-[1.5rem] sm:text-[1.75rem] font-extrabold text-text-main mb-1",
  headerSubtitle: "text-[#64748b] text-[0.9375rem]",
  headerActions: "flex gap-3 flex-wrap w-full md:w-auto",
  exportButton: "btn btn-outline bg-white flex items-center gap-2 font-bold flex-1 justify-center whitespace-nowrap",
  addButton: "btn btn-primary flex items-center gap-2 font-bold py-3 px-5 flex-1 justify-center whitespace-nowrap",
  statsGrid: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-[repeat(auto-fit,minmax(240px,1fr))] gap-4 sm:gap-5 mb-12",
  statCard: "bg-white p-6 rounded-[1.25rem] border border-[#f1f5f9] shadow-[0_4px_20px_rgba(0,0,0,0.02)]",
  statIconWrapper: "w-10 h-10 rounded-xl bg-[#f1f5f9] flex items-center justify-center mb-5",
  statTitle: "text-[#64748b] text-[0.8125rem] font-semibold mb-1",
  statValue: "text-[1.5rem] font-extrabold text-text-main",
  listingsSection: "mb-12",
  listingsHeader: "flex justify-between items-center mb-6 flex-wrap gap-4",
  listingsTitle: "text-[1.25rem] font-extrabold text-text-main",
  searchWrapper: "relative w-full max-w-[500px]",
  searchIcon: "absolute left-4 top-1/2 -translate-y-1/2 text-[#94a3b8]",
  searchInput: "py-2.5 pr-4 pl-10 rounded-xl border border-[#e2e8f0] outline-none text-[0.875rem] w-full",
  emptyListings: "card-premium py-16 text-center text-[#64748b]",
  propertiesGrid: "grid grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-6 justify-items-center max-sm:grid-cols-1 max-sm:px-4",
  propertyActions: "flex-1 flex gap-[0.4rem]",
  statusButton: (status) => `btn btn-outline flex-1 p-2 text-[0.75rem] flex items-center justify-center gap-1 ${status === 'sold' ? 'text-primary border-primary hover:bg-primary-light' : 'text-[#64748b]'}`,
  editButton: "btn btn-outline flex-1 p-2 text-[0.75rem] flex items-center justify-center gap-1",
  deleteButton: "btn btn-outline flex-1 p-2 text-[0.75rem] text-[#ef4444] border-[#fee2e2] flex items-center justify-center gap-1 hover:bg-red-50",
  viewButton: "btn btn-primary p-2 flex items-center justify-center",
  showMoreWrapper: "text-center mt-10",
  showMoreButton: "btn btn-outline py-3 px-10 font-extrabold text-[0.9rem] rounded-xl bg-white shadow-[0_4px_12px_rgba(0,0,0,0.05)] inline-flex items-center gap-2",
  widgetsGrid: "grid grid-cols-[repeat(auto-fit,minmax(300px,1fr))] gap-8 mb-8",
  inquiriesWidget: "bg-white rounded-3xl border border-[#f1f5f9] p-6 shadow-[0_4px_20px_rgba(0,0,0,0.02)]",
  widgetTitle: "text-[1.125rem] font-extrabold text-text-main mb-1",
  widgetSubtitle: "text-[#64748b] text-[0.8125rem] mb-6",
  inquiriesList: "flex flex-col gap-5",
  inquiryItem: "flex justify-between items-center flex-wrap gap-4",
  inquiryLeft: "flex items-center gap-4 min-w-[200px]",
  inquiryIcon: "w-10 h-10 rounded-full bg-[#f1f5f9] flex items-center justify-center border-2 border-white shadow-[0_2px_10px_rgba(0,0,0,0.05)]",
  inquiryName: "font-bold text-[0.875rem] text-text-main",
  inquiryProperty: "text-[0.75rem] text-[#64748b]",
  inquiryRight: "text-right flex-1",
  inquiryDate: "text-[0.7rem] text-[#94a3b8] mb-0.5",
  inquiryStatus: (status) => `py-0.5 px-2 rounded-full text-[0.65rem] font-extrabold uppercase ${status === 'read' ? 'bg-[#f1f5f9] text-[#64748b]' : 'bg-primary-light text-primary'}`,
  noInquiries: "text-center text-[#64748b] p-4",
  tipsWidget: "bg-white rounded-3xl border border-[#f1f5f9] p-6 shadow-[0_4px_20px_rgba(0,0,0,0.02)]",
  tipsList: "flex flex-col gap-4",
  tipCardHighViews: "bg-[#f0fdfa] p-4 rounded-2xl border border-[#ccfbf1]",
  tipTitleHighViews: "text-primary mb-1 flex items-center gap-2 text-[0.875rem]",
  tipTextHighViews: "text-[0.75rem] text-[#134e4a] leading-relaxed",
  tipCardMarket: "p-4 rounded-2xl bg-[#f9fafb]",
  tipTitleMarket: "text-[#4b5563] mb-1 font-bold text-[0.875rem]",
  tipTextMarket: "text-[0.75rem] text-[#6b7280] leading-relaxed",
};
