export const profileStyles = {
  containerWrapper: (role) => role !== 'seller' ? 'bg-bg-alt min-h-screen pt-32 max-lg:pt-28' : 'bg-transparent min-h-auto', 
  mainContainer: (role) => `container fade-in max-w-[800px] mb-16 ${role !== 'seller' ? 'mx-auto pt-12' : 'mx-0 pt-0'}`,
  header: "mb-12 md:text-center md:mb-8",
  pageTitle: "text-[2.5rem] mb-2 md:text-[2rem]",
  pageSubtitle: "text-text-muted",
  card: "card-premium p-12 md:p-6",
  profileHeader: "flex flex-col md:flex-row items-center gap-4 md:gap-8 mb-10 md:mb-16 text-center md:text-left",
  avatarSection: "relative",
  avatarWrapper: "w-[120px] h-[120px] rounded-[2.5rem] bg-primary-light overflow-hidden flex items-center justify-center text-[3rem] font-bold text-primary border-4 border-white shadow-lg",
  avatarImage: "w-full h-full object-cover",
  avatarPlaceholder: "text-primary opacity-60",
  uploadButton: "absolute -bottom-2.5 -right-2.5 bg-primary text-white w-10 h-10 rounded-full flex items-center justify-center cursor-pointer shadow-[0_4px_10px_rgba(0,0,0,0.2)] border-4 border-white z-10 hover:bg-primary-dark transition-colors",
  removeButton: "absolute -top-2.5 -right-2.5 bg-red-500 text-white w-10 h-10 rounded-full flex items-center justify-center cursor-pointer shadow-[0_4px_10px_rgba(0,0,0,0.2)] border-4 border-white z-10 hover:bg-red-600 transition-colors",
  userName: "text-[1.75rem] mb-1 break-all sm:break-normal",
  roleBadge: "badge badge-sale bg-primary-light text-primary px-4 py-2 rounded-xl",
  errorMessage: "p-4 bg-red-100 text-red-600 rounded-xl mb-8",
  editForm: "flex flex-col gap-8",
  label: "block mb-2 text-sm font-semibold",
  input: "w-full p-3.5 rounded-xl border border-border outline-none focus:border-primary transition-colors",
  textarea: "w-full h-[100px] p-3.5 rounded-xl border border-border outline-none resize-none focus:border-primary transition-colors",
  formActions: "flex flex-col md:flex-row gap-4 mt-4",
  saveButton: "btn btn-primary flex-1 flex items-center justify-center gap-2",
  cancelButton: "btn btn-outline flex-1 flex items-center justify-center gap-2",
  infoSection: "flex flex-col gap-10",
  infoItem: "flex items-center gap-6",
  infoIcon: "w-12 h-12 rounded-2xl bg-[#f8fafc] flex items-center justify-center text-primary shrink-0",
  infoLabel: "text-sm text-text-muted mb-0.5",
  infoValue: "font-semibold break-all sm:break-normal",
  editButtonWrapper: "mt-8 pt-8 border-t border-border",
  editProfileButton: "btn btn-primary px-10 py-3.5",
};