export const adminUsersStyles = {
  containerHeader: "flex justify-between items-start mb-8 flex-wrap gap-4",
  headerTitle: "text-[1.75rem] font-extrabold text-text-main mb-1",
  headerSubtitle: "text-text-muted text-[0.875rem]",
  filterWrapper: "relative",
  filterButton: "flex items-center gap-2 px-4 py-2.5 rounded-lg border border-[#e2e8f0] bg-white text-text-main shadow-sm hover:bg-[#f8fafc] transition-all duration-200 cursor-pointer",
  filterDropdown: "absolute right-0 max-sm:left-0 max-sm:right-auto mt-2 w-44 rounded-xl border border-[#e2e8f0] bg-white shadow-lg z-20 overflow-hidden",
  filterOption: (isActive) => `w-full text-left px-4 py-2.5 hover:bg-[#f8fafc] ${isActive ? "font-semibold text-primary" : "text-text-main"}`,
  cardContainer: "card-premium overflow-hidden mb-8 p-0",
  cardHeader: "pt-6 px-6 pb-2",
  cardTitleRow: "flex justify-between items-center mb-4",
  cardTitle: "text-[1.25rem] font-extrabold text-text-main",
  userCount: "text-sm font-semibold text-text-muted",
  userCountSpan: "text-text-main",
  tableWrapper: "overflow-x-auto touch-pan-x",
  table: "w-full border-collapse min-w-[800px]",
  thead: "bg-[#f8fafc] text-[#64748b] text-[0.7rem] font-bold uppercase tracking-[0.05em]",
  tableRow: "border-b border-[#f1f5f9]",
  thUserInfo: "py-4 px-6 text-left",
  thRole: "py-4 px-6 text-center",
  thContact: "py-4 px-6 text-left",
  thStatus: "py-4 px-6 text-center",
  thActions: "py-4 px-6 text-right",
  tdUserInfo: "py-6 px-8",
  userAvatar: "w-10 h-10 rounded-full bg-primary-light text-primary flex items-center justify-center font-bold",
  userInfoName: "font-bold text-[0.9375rem]",
  userInfoId: "text-[0.75rem] text-text-muted",
  tdRole: "py-6 px-6 text-center",
  roleBadge: (role) => `px-3 py-1.5 rounded-full text-[0.75rem] font-bold uppercase ${role === "admin" ? "bg-[#fef3c7] text-[#92400e]" :
    role === "seller" ? "bg-[#dcfce7] text-[#166534]" :
      "bg-[#dbeafe] text-[#1e40af]"
    }`,
  tdContact: "py-6 px-6",
  contactWrapper: "flex flex-col gap-1",
  contactEmail: "text-[0.875rem] flex items-center gap-2 text-text-main",
  contactPhone: "text-[0.875rem] flex items-center gap-2 text-text-main",
  tdStatus: "py-6 px-6 text-center",
  statusBadgeBlocked: "text-[#dc2626] text-[0.8125rem] font-bold inline-flex items-center gap-1.5 justify-center bg-[#fff5f5] py-1 px-2 rounded-lg border border-[#fee2e2]",
  statusBadgeActive: "text-[#10b981] text-[0.8125rem] font-bold inline-flex items-center gap-1.5 justify-center bg-[#f0fdf4] py-1 px-2 rounded-lg border border-[#dcfce7]",
  tdActions: "py-6 px-6 text-right",
  actionsWrapper: "flex gap-2 justify-end",
  blockButton: (isBlocked) => `w-9 h-9 rounded-lg border border-[#e2e8f0] bg-white flex items-center justify-center cursor-pointer hover:bg-gray-50 ${isBlocked ? "text-[#10b981]" : "text-[#f59e0b]"}`,
  deleteButton: "w-9 h-9 rounded-lg border-none bg-[#fef2f2] text-[#dc2626] flex items-center justify-center cursor-pointer hover:bg-red-100",
  emptyState: "py-16 text-center text-text-muted",
};