export const adminContactsStyles = {
  container: "mb-10",
  heading: "text-[2rem] font-extrabold text-text-main mb-2",
  subheading: "text-text-muted text-[0.9rem]",
  card: "card-premium p-0 overflow-hidden",
  cardHeader: "border-b border-[#f1f5f9] p-6 flex justify-between items-center",
  cardTitle: "text-[1.2rem] font-extrabold",
  emptyState: "p-16 text-center text-text-muted",
  emptyIcon: "opacity-20 mb-4 mx-auto",
  contactList: "flex flex-col",
  contactItem: (index, total) => `p-5 sm:p-8 bg-white transition-all duration-300 ease-in-out border-b ${index !== total - 1 ? 'border-[#f1f5f9]' : 'border-transparent'}`,
  contactHeader: "flex flex-col sm:flex-row justify-between items-start mb-6 gap-4 sm:gap-0",
  avatarWrapper: (role) => `w-14 h-14 rounded-full flex items-center justify-center font-bold text-[1.25rem] shrink-0 ${role === 'seller' ? 'bg-[#dcfce7] text-[#166534]' : 'bg-[#dbeafe] text-[#1e40af]'}`,
  nameBadgeContainer: "flex items-center gap-3 mb-1 flex-wrap",
  name: "text-[1.1rem] font-extrabold text-text-main",
  roleBadge: (role) => `text-[0.7rem] px-[0.6rem] py-[0.2rem] rounded-full font-bold uppercase ${role === 'seller' ? 'bg-[#dcfce7] text-[#166534]' : 'bg-[#dbeafe] text-[#1e40af]'}`,
  contactDetails: "flex flex-col sm:flex-row gap-2 sm:gap-6 sm:flex-wrap mt-2 sm:mt-0",
  detailItem: "flex items-center gap-[0.4rem] text-[0.85rem] text-text-muted break-all sm:break-normal",
  messageBox: "bg-[#f8fafc] p-4 sm:py-5 sm:px-6 rounded-2xl text-[0.95rem] leading-[1.6] text-[#334155] border border-[#f1f5f9]",
};

export const adminInquiriesStyles = {
  headerContainer: "mb-12",
  headerTitle: "text-[2rem] font-extrabold text-text-main mb-2",
  headerSubtitle: "text-text-muted",
  listContainer: "admin-inquiries-list flex flex-col gap-6",
  inquiryCard: "card-premium p-6 md:p-8",
  cardTopSection: "flex flex-col sm:flex-row justify-between items-start mb-6 border-b border-[#f1f5f9] pb-6 gap-4 sm:gap-4",
  propertyInfoWrapper: "flex items-center gap-4",
  propertyIconWrapper: "bg-primary-light p-3 rounded-xl text-primary",
  propertyTextWrapper: "w-full sm:w-auto text-left",
  propertyTitle: "font-bold",
  propertyId: "text-xs text-text-muted",
  dateWrapper: "text-sm text-text-muted text-left sm:text-right w-full sm:w-auto",
  dateIcon: "inline align-middle mr-1",
  detailsGrid: "grid grid-cols-1 sm:grid-cols-2 gap-4 md:gap-6 mb-6",
  detailCard: "bg-[#f8fafc] p-4 md:p-5 rounded-2xl border border-[#f1f5f9]",
  detailLabel: "text-xs font-bold text-text-muted uppercase mb-3 tracking-widest",
  detailName: "font-bold text-text-main mb-1",
  detailEmail: "text-sm text-text-muted break-all",
  messageContainer: "bg-bg-alt p-6 rounded-2xl border-l-[4px] border-primary",
  messageHeader: "flex items-center gap-2 mb-2 text-primary font-bold text-sm",
  messageText: "italic text-text-main leading-relaxed",
  emptyState: "card-premium py-24 px-8 text-center",
  emptyIconWrapper: "text-text-muted mb-4",
  emptyText: "text-text-muted",
};