export const editPropertyStyles = {
  pageContainer: "fade-in px-4 py-8 md:py-12 w-full mx-auto dashboard-content",
  innerContainer: "max-w-[900px] w-full mx-auto",
  headerWrapper: "mb-12 text-center",
  pageTitle: "text-[clamp(1.75rem,5vw,2.5rem)] mb-4 text-text-main font-extrabold",
  pageSubtitle: "text-text-muted text-base",
  formContainer: "card-premium p-6 md:p-10",
  section: "mb-12",
  sectionHeader: "flex items-center gap-4 mb-8",
  sectionIndicator: "w-1 h-6 bg-primary rounded-sm",
  sectionTitle: "text-xl font-extrabold text-text-main",
  sectionContent: "flex flex-col gap-6",
  label: "block mb-2.5 text-sm font-bold text-text-main",
  input: "w-full py-3.5 px-4 rounded-xl border border-[#e2e8f0] outline-none bg-white text-[0.9375rem] focus:border-primary transition-colors",
  textarea: "w-full h-[120px] py-3.5 px-4 rounded-xl border border-[#e2e8f0] outline-none resize-none bg-white text-[0.9375rem] leading-relaxed focus:border-primary transition-colors",
  select: "w-full p-3.5 rounded-xl border border-[#e2e8f0] outline-none bg-white cursor-pointer focus:border-primary transition-colors",
  twoColumnGrid: "grid grid-cols-1 md:grid-cols-[repeat(auto-fit,minmax(280px,1fr))] gap-8 mb-12",
  threeColumnGrid: "grid grid-cols-1 sm:grid-cols-3 gap-4",
  twoColumnGridInner: "grid grid-cols-1 sm:grid-cols-2 gap-4",
  amenitiesGrid: "grid grid-cols-[repeat(auto-fill,minmax(150px,1fr))] gap-4",
  amenityLabel: (isSelected) => `flex items-center gap-3 cursor-pointer p-3 rounded-xl border transition-all duration-200 ${isSelected ? 'bg-primary-light border-primary' : 'bg-[#f8fafc] border-[#e2e8f0]'}`,
  amenityCheckbox: "accent-primary w-4 h-4",
  amenityText: (isSelected) => `text-sm font-semibold ${isSelected ? 'text-primary' : 'text-text-main'}`,
  imageGrid: "grid grid-cols-[repeat(auto-fill,minmax(100px,1fr))] gap-4",
  imageCard: "relative aspect-square rounded-xl overflow-hidden border-2 border-[#f1f5f9]",
  imageCardNew: "relative aspect-square rounded-xl overflow-hidden border-2 border-dashed border-primary",
  imageCardImg: "w-full h-full object-cover",
  removeImageBtn: "absolute top-1 right-1 bg-[#dc2626] text-white border-none rounded-full w-5 h-5 flex items-center justify-center cursor-pointer z-10",
  imageBadgeExisting: "absolute bottom-0 left-0 right-0 bg-primary text-white text-[0.6rem] text-center py-0.5 font-bold tracking-widest",
  imageBadgeNew: "absolute bottom-0 left-0 right-0 bg-[#10b981] text-white text-[0.6rem] text-center py-0.5 font-bold tracking-widest",
  uploadCard: "aspect-square border-2 border-dashed border-[#cbd5e1] rounded-xl flex flex-col items-center justify-center cursor-pointer relative bg-[#f8fafc] transition-colors hover:border-primary",
  uploadInput: "absolute inset-0 opacity-0 cursor-pointer",
  uploadText: "text-xs font-bold text-[#64748b] mt-1.5",
  formActions: "mt-12 flex justify-center flex-wrap gap-5 border-t border-[#f1f5f9] pt-10",
  cancelButton: "btn btn-outline py-3.5 px-10 font-bold min-w-[140px]",
  submitButton: "btn btn-primary py-3.5 px-12 font-bold min-w-[180px]",
};