export const footerStyles = {
footer: "bg-white border-t border-[#e2e8f0] pt-24 pb-0",
footerMainGrid: "footer-main-grid grid grid-cols-[1.5fr_1fr_1fr_1.5fr] gap-16 mb-16 max-lg:grid-cols-2 max-lg:gap-12 max-sm:grid-cols-1 min-[640px]:max-[1024px]:justify-items-center",
footerBrand: "footer-brand-section max-sm:text-center max-sm:flex max-sm:flex-col max-sm:items-center",
brandLogo: "flex items-center gap-2 text-2xl font-extrabold text-primary mb-6",
brandIcon: "bg-primary text-white py-1.5 px-2.5 rounded-xl text-base",
brandDesc: "text-text-muted mb-8 leading-relaxed text-[0.9375rem]",
socialIcons: "flex gap-4",
socialIcon: "social-icon w-9 h-9 rounded-full bg-bg-alt flex items-center justify-center text-text-main transition-all duration-300 hover:-translate-y-1 hover:bg-primary hover:text-white",
footerHeading: "text-[1.125rem] font-extrabold mb-8",
footerLinks: "flex flex-col gap-5 text-text-muted text-[0.9375rem]",
footerLink: "footer-link transition-colors duration-300 hover:text-primary hover:underline",
contactInfo: "flex items-center gap-3",
contactInfoStart: "flex items-start gap-3",
contactIcon: "shrink-0 mt-[2px] text-xl",
newsletterDesc: "text-text-muted text-[0.875rem] mb-6 leading-relaxed",
newsletterInputWrapper: "relative",
newsletterInput: "w-full py-4 pr-[85px] pl-5 rounded-2xl border border-[#e2e8f0] bg-bg-alt outline-none text-[0.875rem] focus:border-primary transition-colors",
newsletterButton: "btn btn-primary absolute right-1.5 top-1.5 bottom-1.5 px-5 rounded-xl text-[0.8125rem]",
bottomBar: "border-t border-[#e2e8f0] py-8 flex flex-col gap-4 text-[0.875rem] text-text-muted",
bottomBarFlex: "flex justify-between items-center flex-wrap gap-4 max-sm:flex-col-reverse max-sm:justify-center",
footerLegalLinks: "flex gap-8 max-sm:w-full max-sm:justify-center max-sm:flex-wrap max-sm:gap-4",
designCredit: "flex justify-center items-center gap-2 pt-2",
designLogo: "w-5 h-5 object-contain",
designLink: "font-semibold text-primary hover:text-blue-700 hover:underline transition-colors duration-300"
};