export const heroStyles = {
bgMain: "bg-bg-main",
container: "container",
heroSection: "fade-in items-center justify-center hero-section pt-32 pb-16 xl:px-40 md:px-20 flex items-center gap-16 overflow-hidden md:flex-col lg:flex-col xl:flex-row max-lg:flex-col max-lg:text-center max-lg:pt-28 max-lg:pb-8 max-lg:px-4 max-lg:gap-8",
heroContent: "hero-content flex-1 max-lg:flex max-lg:flex-col max-lg:items-center",
badge: "badge bg-primary-light text-primary-dark mb-6 inline-block",
heroTitle: "hero-title text-[clamp(2rem,5vw,4.5rem)] mb-6 transition-all duration-300 max-lg:text-[clamp(1.75rem,8vw,2.5rem)] max-lg:leading-tight max-lg:text-center",
textGradient: "text-gradient",
heroSubtitle: "hero-subtitle text-[1.125rem] text-text-muted mb-12 max-w-[540px] max-lg:text-base max-lg:mb-10 max-lg:mx-auto max-lg:text-center max-lg:px-4",
searchForm: "glass search-form p-5 rounded-[2rem] flex items-center gap-4 shadow-[0_20px_40px_rgba(0,0,0,0.08)] max-w-[900px] border border-white/50 relative z-10 max-lg:flex-col max-lg:w-full max-lg:max-w-[500px] max-lg:mx-auto max-lg:gap-2 max-lg:rounded-[1.5rem]",
searchField: "search-field flex-[1.2] flex items-center gap-3 py-2 px-3 transition-all duration-300 min-w-[220px] max-lg:w-full max-lg:py-4 max-lg:px-2 max-lg:border-b max-lg:border-[#f1f5f9]",
textPrimary: "text-primary",
flexCol: "flex flex-col flex-1",
labelSmall: "text-[0.7rem] font-extrabold text-text-muted uppercase tracking-[0.05em] mb-1",
inputTransparent: "border-none bg-transparent outline-none w-full text-base font-semibold text-text-main",
searchDivider: "search-divider w-[1px] h-[44px] bg-border-color opacity-60 shrink-0 max-lg:hidden",
searchButton: "btn btn-primary search-button h-[64px] min-w-[140px] rounded-[1.25rem] text-base font-bold shadow-[0_12px_24px_rgba(13,148,136,0.25)] flex items-center justify-center gap-2 max-lg:w-full max-lg:h-[56px] max-lg:rounded-2xl max-lg:mt-2",
statsContainer: "stats-container flex gap-[clamp(1rem,3vw,4rem)] mt-16 max-lg:justify-center max-lg:gap-8 max-md:flex-wrap",
statItemFlex: "flex-1 max-md:flex-none max-md:shrink-0 max-md:basis-[120px]",
statNumber: "text-[clamp(1.5rem,3vw,2rem)] font-extrabold",
statLabel: "uppercase text-[0.7rem] text-text-muted font-extrabold tracking-[0.05em]",
statItemBorder: "stat-item border-l border-border-color pl-[clamp(1rem,3vw,4rem)] flex-1 max-lg:pl-8 max-md:border-none max-md:pl-0 max-md:flex-none max-md:shrink-0 max-md:basis-[120px]",
heroImageContainer: "hero-image-container flex-1 relative",
imageWrapper: "rounded-[3rem] overflow-hidden shadow-[0_40px_80px_-20px_rgba(0,0,0,0.25)] relative",
heroImage: "w-full h-[600px] object-cover",
verifiedBadge: "glass absolute bottom-8 left-8 p-6 rounded-3xl flex items-center gap-4 max-w-[300px]",
badgeIconWrapper: "bg-primary-light p-3 rounded-2xl",
badgeTitle: "text-[0.9375rem] m-0 font-bold",
badgeText: "text-[0.75rem] text-text-muted m-0",
preApproved: "badge bg-primary/10 text-primary text-[0.625rem]",
categorySection:"py-18 bg-bg-alt",
categoryHeader: "category-header flex justify-between items-end mb-12 max-sm:flex-col max-sm:items-start max-sm:gap-6",
categoryGrid:"category-grid grid grid-cols-[repeat(auto-fit,minmax(240px,1fr))] gap-6 max-sm:grid-cols-2 max-sm:gap-4",
categoryCard:"category-card py-10 px-6 text-center cursor-pointer bg-white rounded-3xl border border-[#e2e8f0] transition-all duration-300",
categoryName:"mb-2 text-xl font-bold max-sm:text-base",
};